services:
  server:
    image: ${IMAGE_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.entrypoints=secure"
      - "traefik.http.routers.nextjs.rule=Host(`omen-taro.ru`)"
      - "traefik.http.routers.nextjs.tls=true"
      - "traefik.http.routers.nextjs.tls.certresolver=default"
    env_file: .env
    ports:
      - 3001:3001
    networks:
      omen:
        aliases:
          - nextjs

networks:
  omen:
    external: true
    driver: bridge
